### ISSUE TITLE
Search bar

### ISSUE THREAD

**Issue by rmcguire6** [chingu-voyages/v30-geckos-team-04#20]
**__User Story Description__**
As a user
I want to search for specific country or region
So I can find out about the air quality

**__Steps to Follow (optional)__**
- [ ] Step #1
- [ ] Step #2
- [ ] Additional steps as necessary

**__Additional Considerations__**
Any supplemental information including unresolved questions, links to external resources, screenshots, etc.

**Comment by jo-soyoung** [comment]
Include in "Home Page" epics
